name: CI RCLC Rolling

on:
  push:
    branches: [ rolling ]
  pull_request:
    branches: [ rolling ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 6 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        ros_distribution: [ rolling ]
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: rolling
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@0.6.3
      with:
        use-ros2-testing: true
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - name : Download and install rclc-dependencies
      run: |
        apt-get install ros-${{ matrix.ros_distribution }}-osrf-testing-tools-cpp
        apt-get install ros-${{ matrix.ros_distribution }}-test-msgs
        apt-get install ros-${{ matrix.ros_distribution }}-rclcpp-action
        apt-get install ros-${{ matrix.ros_distribution }}-mimick-vendor
        apt-get -y install ros-${{ matrix.ros_distribution }}-performance-test-fixture
    - uses : ros-tooling/action-ros-ci@0.3.5
      with:
        package-name: "rclc rclc_examples rclc_lifecycle rclc_parameter"
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-defaults: |
          {
            "build": {
              "mixin": [ "coverage-gcc" ]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1
      with:
        file: ros_ws/lcov/total_coverage.info
